### ISSUE TITLE
Misattribution

### ISSUE THREAD

**Issue by R055A** [Dna072/drl-jss#11]
Attribution for authorship of original repository work extended on in this repository is deleted in misrepresentation.

The following is a visualisation of contributions to this repository, with exception to those being excluded in the modification from the original documented repository, which should also be accurately attributed with contributions evidently remaining.

![Contributors to Dna072_drl-jss](https://github.com/user-attachments/assets/3538376a-7cef-4036-b726-6d9fe4ac6c17)

**Comment by Dna072** [comment]
Let me remind you that this is the project we started working on as a team, and then diverged with you working on yours and Nicolas and I working on our version. You removed us from the project without and consultation as if you owned the project and no one commented on that. This version is extensively modified and if I will be giving a reference to the project, I will be referencing the project repo and not individuals.

**Comment by R055A** [comment]
> Let me remind you that this is the project we started working on as a team, and then diverged with you working on yours and Nicolas and I working on our version. You removed us from the project without any consultation as if you owned the project and no one commented on that. This version is extensively modified and if I will be giving a reference to the project, I will be referencing the project repo and not individuals.

If what you say is true, although we don't need to remind anyone it isn't, then you should not be using my contributions, especially without my permission, especially without ethical acknowledgement to my and others' authorship, as is an academic obligation and responsibility. 

It's not the same as presenting others' contributions as if owning them without consultation when in team collaboration immediately following meticulous repeat taught instruction in all private meeting time, although without comment, of course. 

I don't see why you can't claim "diversion" solely as you wish, but I do see why you can't deny my contributions regardless of only diverging from fair attribution in this and, although seemingly too late and needless to say, you should only speak for yourself (especially regarding my thoughts, before they can even be thought?!).

I will be further referencing to this repository as a shadow repository for the time being. although unsure if it is the correct term for such a problem. Don't get me wrong though, I have years of experience in similar circumstances, especially in the field of data science when being grouped with those of less background and understanding in software development, project management, and collaboration, etc. There have been other circumstances where once I contribute, usually first, and in many cases by the end of the project - as the statistics on my GitHub profile suggest - only, there is some form of "diversion", but never without my contributions and never with complaint or explanation, or even knowledge much of the time. Some falsely claim to be participating in my individual contributions, such as in a case immediately prior to collaborating on this project with you as I suspect you already know (the figurative holes burnt into the back of my head during the lectures for this project can be testament to that), but the commit log and all other documentation always proves otherwise, and that I alone was passed for that project following the preliminary presentation should rectify that argument. Some claim I am completing their task(s), but again all planning, documentation and contribution logs etc. always suggest otherwise, and it is usually not until the final moments of a project these false claims are made, or just after its completion, with the tasks being left idle until the final moments when paramount for the projects successful completion. To be fair, this has actually been done to me more than once regardless of planning and documentation, with others moving in on my work just before I am ready to push my contributions regardless of ample time to complete the project and more so little to no time remaining to remedy the situation for myself - although I must take some fault for having my work publicly visible.

I should clarify that never have I excluded anyone in a collaborative group project, done anything to undermine or sabotage their work, nor conspired in any way, and especially never just done all the work if ever the case without utter necessity in the final moments alone merely for completion sake, and have always worked more toward a fair plan involving everyone to the best of their abilities and desires than toward the project completion itself, especially just for myself. Unfortunately, I can never say I have always received the same treatment. Many times, many don't ever bother attempting to contribute, or sometimes even collaborate, with some even declaring their full intent to not participate or be involved from the start, and disappear for times, if ever there beforehand, many times to inevitably return to (further) blame and attack in some form or another - much like this case scenario, although never before has pending high-priority task work been blocked for one member, not even in the group, blatantly disappearing for what could be a third of the Agile project timeline without any online contribution or communication - and very likely only for holiday considering it being their plan to do all their envisioned share of work before this - to return with psycho antisocial attitude only to insanely attack and force a one-sided split under false pretenses and pretext with all - and only by then with all of my - only meaningful - contributions (take a good hard look at the screen shot below representing contributions at the time of the split, but take all the time you need, as if you haven't already, thank you - these are the real contributions I am referring to BTW, not what can only be repeat pushes of prior contributions to explain the increase in my statistics since, and yours before the split!!!) - the overdue pending task work required to complete the project. Some have even blatantly claimed I am the only one to not contribute when in fact the false claimant is the only one evidently without contributions pushed to the project repository - much like this case scenario, although excluding last moment "review", of course, and much like the initial case scenario at the university - before cheat-gpt could be used as a weapon - when collaborating with whom ironically following outrageous false claims of complete interference is now a supervisor for this project completely interfered with - but this was on the eve of the global pandemic, and the direct and indirect consequences of my already being significantly affected more than once without fair consideration had unfortunately mislead them to make such mistakes which seem to continue today.

There have also been far, far worse circumstances I have experienced than before data science, spanning years since 2018 including the only other case - I am aware - of blatant false accusations and labeling of my not working throughout an entire semester against all logic, sanity and bountiful evidence and witnessing, and far worse, and although I survived, albeit severely victimised enough already beforehand directly relating to this alone, unfortunately the consequences of which also continue today. The consequences continue not much different than when they directly affected the aforementioned exemplified circumstances when others were pushing my task work before me, already by then in the fourth - and almost the worst if not for the first - year of direct (100% oppressive) effect since 2018 alone, which is not surprising being its all a climactic continuation in itself from prior years in a cyclic nature of victimisation (and none of these are close to what I refer to on my GitHub profile). These events could be considered only natural though considering the madness (like something out of mad max) and unimaginable bias ignorance applied to the problems, although mediocre in self, not to mention intent or conceived dependency, feigned importance more than importance itself, etc, etc, etc. I have seen thesis reports written in perfect English by those claiming to not have any such skills in - very convincingly - manipulating me to do all the work (with exception to pointing a finger of pretense while walking out as others walk in, if not attempting to convince me the only female in the group is a liar based solely on a cafe-scene Facebook profile photo they have no right to stalk nor intimidate) in other projects. However, never before have I experienced a circumstance like this involving a clone repository extended on for a thesis with attribution of mine and other's authorship blatantly removed although clearly still evident (refer to visualisation of contributions in the original comment) regardless of significant obfuscation otherwise.

We started working as a team on the same repository and finished as a team on the same repository, but although this is not that repository, the work is still from the same repository and team, and includes numerous significant contributions from others (refer to image at bottom of this comment), with exception to what is excluded in the true default `main` branch, at least in that branch in this obfuscated version of the repository, which seems to be the only real divergence in the project. Which leads me to query, if the `main` branch remains - at least in an obfuscated state - regardless of any functional purpose as supposedly diverged from - rather than evidently converged with - then why too do none of the other development branches - although never merged (regardless of immediate resolving of issues, let alone requested) - to the now renamed `master` development branch remain? When merely taking time to consider my consistent and meticulous interactive reviewing and inevitable passing of the PR for the "`master`" branch, why not is it just merged to `main` in the shadow repository, as to my assumption - although I've never done this myself to know - it should merge seamlessly without the remainder of contributions to `main` by myself following November 29th 2023 being included.

Let me ask a question, can anyone further obfuscate this shadow repository without your permission or acknowledgement of your contributions and authorship for any illogical (underperforming erratic/absent schizo poser) pretense? The implementation of `stable-baselines3`, and code structure and style in this repository remains somewhat consistent with the original project after all, at least as stated in the documentation, although the automated CI workflow runs for (otherwise weeks of redundant "testing" - without change requests, let alone feedback) PR commit pushes are turned off following the creation of this repository on January 20th 2024 (see images below).

If you say you're removed from the project and didn't comment on it then you shouldn't have rights to it should you, just like you shouldn't have rights to my individual work specifically in servitude to your "thesis" by false authority as already attempted during the project you state as no longer participating in. What is it now though, you diverged, got removed or are converging all along?

You also shouldn't be referencing a private repository if you do truly intend to reference the original (and not this obfuscated clone modification) project. I assume this means you have not yet finished your thesis. I don't see it yet on DiVA, and see many from your specialisation are behind the initial deadline on the thesis presentation resit schedule, but also a few similar projects already published. I hope you have learned something here to help you in that, and in contrary to you, I wish the best of luck. I look forward to reading your work!

### Images

* Automated CI workflow runs (excluding all contributions to `main` following November 29th 2023) before being turned off:
![Workflow runs · Dna072_drl-jss](https://github.com/user-attachments/assets/12e600a4-3e32-4871-8e01-1ab26d385865)

* Initial automated CI workflow run for PR #27 in the original repository:
![image](https://github.com/user-attachments/assets/95176c82-f1e9-47ef-a0e5-bb38b4566784)

* The original repository project contributions visualised for reference (including `jupyter notebook` file changes by others):
![image](https://github.com/user-attachments/assets/090f9007-1988-46bb-a98b-300de3824666)

I don't think we have met since the state of the project in the bottom visualisation. This is very likely because I fell unwell with multiple severe infections requiring months of recovery at the same and different times somehow like last year and at approximately the same time my laptop was mysteriously damaged beyond use somehow not already although repetitively violently attacked, even on budget flights, such as like in your profile image. At least on my part.
